### ISSUE TITLE
"mysql-build -v 5.7.5-m15" failed on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by iku000888** [kamipo/mysql-build#21]
Cloned the repository, exported command to path and ran 
$mysql-build -v 5.7.5-m15 ./5.7.5
Which resulted in below msg.
Not at all sure what went wrong (first time seeing cmake and trying to build mysql)
and for that matter this is my first issue ever raised.

![screenshot from 2015-05-02 21 36 56](https://cloud.githubusercontent.com/assets/11477585/7441103/7f2a0412-f113-11e4-866d-0a0e66ee27fd.png)

**Comment by kamipo** [comment]
Although `mysql-build` to help to automate the build, the build dependency is necessary to prepare on their own.

It seems to configure incompleted by `cmake`.

Could you see `build.log` on `/home/ikuru/mysql-build/build.log`?

**Comment by iku000888** [comment]
Thanks for replying! 
I should always read log files before posting... orz...

Did find below message in log file.
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
CMake Error at cmake/readline.cmake:85 (MESSAGE):
  Curses library not found.  Please install appropriate package,

Seemed necessary to install libncurses5-dev, so went a head and did that,
http://stackoverflow.com/questions/4678926/cmake-cant-find-curses
and now a different error shows up.

[ 57%] Building CXX object storage/perfschema/CMakeFiles/perfschema.dir/cursor_by_thread_connect_attr.cc.o
[ 58%] Building CXX object storage/perfschema/CMakeFiles/perfschema.dir/table_session_connect.cc.o
[ 58%] Building CXX object storage/perfschema/CMakeFiles/perfschema.dir/table_session_connect_attrs.cc.o
[ 58%] Building CXX object storage/perfschema/CMakeFiles/perfschema.dir/table_session_account_connect_attrs.cc.o
Linking CXX static library libperfschema.a
[ 58%] Built target perfschema
make: *** [all] Error 2

(Maybe related)
http://stackoverflow.com/questions/23042715/mysql-build-error-linking-cxx-executable-pfs-connect-attr-t

Anyhow, it seems that mysql-build is doing its job: i.e fetch specified version of source code
& execute the build process.

If this is indeed beyond the scope of mysql-build, 
please let me know whether I should close this issue.
I will probably post this to developer mailing list or somewhere else.

**Comment by iku000888** [comment]
Attempted building 5.7.7-rc, and it somehow worked...
I am content for now, so I will close this issue.

Thank you Kamipo-san.
I appreciate this project, as it simplifies many complications of building Mysql from source.

**Comment by kamipo** [comment]
You’re welcome :smile:
